### PR TITLE
fix the extension

### PR DESCRIPTION
**Pull request by corbinschwartz**
The extension wasn't working, this fixes it.

### CODE REVIEW

**Comment by damianw** [comment]
👍

**Comment by corbinschwartz** [comment]
Wait, undo the merge! I found a huge issue with it. Basically if you click anywhere in the body, not just the collapse button, it collapse/expands it!

This makes replying to comments impossible.

**Comment by corbinschwartz** [comment]
Looking at it now, it appears that that's what your original code did. I'm gonna fix it.

**Comment by damianw** [comment]
Hah, no worries. :)
Yeah, I remember that bug. I stopped using this a while ago so I haven't much bothered to fix it. Will take a look at your other PR though.

**Pull request merged**
